In [1]:
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
import os
from tempfile import mkstemp
import subprocess
from IPython.display import Image
from IPython.core.display import display
from sklearn.svm import SVC
from sklearn.tree.export import export_graphviz
from sklearn.model_selection import GridSearchCV

import matplotlib.pyplot
from xgboost.sklearn import XGBClassifier
from sklearn import preprocessing
from sklearn.preprocessing import Imputer
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.grid_search import GridSearchCV
from sklearn import cross_validation

C:\Users\Mustang8\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\Mustang8\Anaconda3\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [2]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_gaussian_quantiles

Input:データセット読み込み

from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

X = pd.DataFrame(cancer.data)

y=pd.DataFrame(cancer.target)

Dataset = pd.concat([ca_data,ca_targe],axis=1)

In [297]:
z1 = pd.DataFrame([1 ,0],  columns = ['z1'], index = ["x1","x2"])
z2 = pd.DataFrame([-1 ,0], columns = ['z2'], index = ["x1","x2"])
z3 = pd.DataFrame([0 ,1],  columns = ['z3'], index = ["x1","x2"])
z4 = pd.DataFrame([0 ,-1], columns = ['z4'], index = ["x1","x2"])

Z = pd.concat([z1,z2,z3,z4], axis = 1).T

Y = pd.DataFrame([1,1,-1,-1], index = ["z1","z2","z3","z4"], columns = ["target"])

In [298]:
D = pd.concat([Z,Y], axis=1)

分類器の作成

In [299]:
#分類器の作成

def h1(x1,x2):
    if x1 > -0.5:
        target = +1
    else:
        target = -1
    return target
        
def h2(x1,x2):
    if x1 > -0.5:
        target = -1
    else:
        target = +1

    return target        
        
def h3(x1,x2):
    if x1 > 0.5:
        target = +1
    else:
        target = -1
    return target  

def h4(x1,x2):
    if x1 > 0.5:
        target = -1
    else:
        target = +1
    return target  
        
def h5(x1,x2):
    if x2 > -0.5:
        target = +1
    else:
        target = -1
    return target  
        
def h6(x1,x2):
    if x2 > -0.5:
        target = -1
    else:
        target = +1
    return target  
        
def h7(x1,x2):
    if x2 > 0.5:
        target = +1
    else:
        target = -1
    return target  
        
def h8(x1,x2):
    if x2 > 0.5:
        target = -1
    else:
        target = +1
    return target  

In [300]:
hh =[h1,h2,h3,h4,h5,h6,h7,h8]

# Process:

In [301]:
#process1 重み分布の初期化
N = len(D) #データセットの大きさ
weightsT = np.zeros((100,N))
weights= np.ones(N)/N #初期重み分布
weightsT[0] =weights

In [302]:
T =range(3)
count =np.zeros(8)

In [303]:
for num in T:
    a1= h1(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a1):
        count[0] +=count[0]+1
    else:
        count[0] = count[0]

    a2 = h2(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a2):
        count[1] += count[1]+1
    else:
        count[1] = count[1]

    a3 = h3(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a3):
        count[2] +=count[2] +1
    else:
        count[2] = count[2]

    a4 =h4(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a4):
        count[3] +=count[3]+1
    else:
        count[3]=count[3]

    a5 = h5(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a5):
        count[4] += count[4] +1
    else:
        count[4]=count[4]
    a6 = h6(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a6):
        count[5] += +1
    else:
        count[5] = count[5]

    a7 = h7(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a7):
        count[6] +=+1
    else:
        count[6] = count[6]

    a8 = h8(D["x1"][num],D["x2"][num])
    if(D["target"][num] == a8):
        count[7] = count[7]+1
    else:
        count[7] = count[7]

In [304]:
mean = np.zeros(8)

for i in range(8):
    mean[i] = (N-count[i])/N

In [305]:
min =1
for i in range(7):
    if(abs(mean[i]) < min):
        min = mean[i]
        A = mean[i]

In [306]:
e = min
if (e < 0.5):
    alpha = 0.5 *np.log((1-e)/e) #e:error_rate

In [307]:
alpha

0.54930614433405489

In [308]:
weights

array([ 0.25,  0.25,  0.25,  0.25])

In [312]:
D["target"][3] * h2(D["x1"][3],D["x2"][3])

1

In [313]:
sum_weights = 0


for num in range(4):
        weights[num] = weights[num] * np.exp( -alpha *  D["target"][num] * h2(D["x1"][num],D["x2"][num]))
        sum_weights = sum_weights + weights[num]

In [314]:
weights

array([ 0.4330127 ,  0.14433757,  0.14433757,  0.14433757])

In [293]:
real_weights = weights / sum_weights
real_weights

array([ 0.04316453,  0.31894516,  0.31894516,  0.31894516])

In [315]:
e1 = real_weights[1]/1

In [316]:
alpha1 = 0.5 * np.log((1-e1)/(e1)) #e:error_rate

In [317]:
alpha1

0.37931183783975664

In [68]:
plt.figure(figsize=(10, 5))

In [69]:
plt.subplot(121)
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, plot_step),
                     np.arange(y_min, y_max, plot_step))

Z = bdt.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)
cs = plt.contourf(xx, yy, Z, cmap=plt.cm.Paired)
plt.axis("tight")

TypeError: unhashable type: 'slice'