In [299]:
import math
from matplotlib import pyplot as plt
import numpy as np
import inspect
import pandas as pd
import random

基本関数定義

In [363]:
def h1(x,y):
    if x > -0.5:
        return 1
    else:
        return -1

def h2(x,y):
    if x > -0.5:
        return -1
    else:
        return 1

def h3(x,y):
    if x > 0.5:
        return 1
    else:
        return -1

def h4(x,y):
    if x > 0.5:
        return -1
    else:
        return 1
def h5(x,y):
    if y > -0.5:
        return 1
    else:
        return -1

def h6(x,y):
    if y > -0.5:
        return -1
    else:
        return 1

def h7(x,y):
    if y > 0.5:
        return 1
    else:
        return -1

def h8(x,y):
    if y > 0.5:
        return -1
    else:
        return 1
    
base = [h1, h2, h3, h4, h5, h6, h7, h8]

初期化

In [364]:
train = np.array([[1,0,1],[-1,0,1],[0,1,-1],[0,-1,-1]])
numdata = len(train)
d = np.array([1/numdata]*numdata)

In [ ]:
for iterations in range(len(base)):
    learn = []
    for i in range(len(base)):
        for j in range(len(train)):
            ans = base[i](train[j,0], train[j,1])
            learn.append(ans)

    learn = np.reshape(learn,(len(base), 4))
    learn = learn.T
    
    er = []
    for i in range(len(base)):
        error = 0.0
        for j in range(len(learn)):
            error = error + d[j]* (1-(learn[j,i]* train[j,2]))# obj = learn のときerrorが0になる
        error = 0.5* error
        er.append(error)
    
    a = np.c_[base, er]
    b = []
    for i in range(len(base)):
        if a[i,1] < 0.5:
            b.append(a[i])
    b = np.array(b)
    h, e = np.split(b, 2, axis=1)

訓練データに弱学習器apply

In [365]:
pred = []
for i in range(len(base)):
    for j in range(len(train)):
        ans = base[i](train[j,0], train[j,1])
        pred.append(ans)

pred = np.reshape(pred, (len(base), 4))
pred = pred.T
pred

array([[ 1, -1,  1, -1,  1, -1, -1,  1],
       [-1,  1, -1,  1,  1, -1, -1,  1],
       [ 1, -1, -1,  1,  1, -1,  1, -1],
       [ 1, -1, -1,  1, -1,  1, -1,  1]])

誤差計算

In [366]:
er = []
for i in range(len(base)):
    error = 0.0
    for j in range(len(pred)):
        error = error + d[j]* (1-(pred[j,i]* train[j,2])) # obj = learn のときerrorが0になる
    error = 0.5* error
    er.append(error)
er

[0.75, 0.25, 0.25, 0.75, 0.25, 0.75, 0.75, 0.25]

In [367]:
a = np.c_[base, er]
a

array([[<function h1 at 0x09F8BC00>, 0.75],
       [<function h2 at 0x09F8BBB8>, 0.25],
       [<function h3 at 0x09F8BB70>, 0.25],
       [<function h4 at 0x09F8BB28>, 0.75],
       [<function h5 at 0x09F8B8E8>, 0.25],
       [<function h6 at 0x09F8B8A0>, 0.75],
       [<function h7 at 0x09F8B930>, 0.75],
       [<function h8 at 0x09F8B978>, 0.25]], dtype=object)

最小誤差を持つ基本関数を抽出(基本学習アルゴリズム)

In [368]:
b = []
for i in range(len(base)):
    if a[i,1] < 0.5:
        b.append(a[i])
b = np.array(b)
h, e = np.split(b, 2, axis=1)
h = h.T
h = h.tolist()
h = [h2, h3, h5, h8]

In [372]:
for k in range(len(h)):
    
    #基本関数適応
    pred = []
    for j in range(len(train)):
        ans = h[0](train[j,0], train[j,1])
        pred.append(ans)

    pred = np.reshape(pred,(1, 4))
    pred = pred.T
    
    #誤差計算
    error = 0.0
    for j in range(len(pred)):
        error = error + d[j]* (1-(pred[j,0]* train[j,2])) # obj = pred のときerrorが0になる
    error = 0.5* error
    
    #重み計算
    al = 0.5* math.log((1-error)/error)
    
    #分布更新
    sum = 0.0
    for i in range(numdata):
        sum = sum + math.exp(-1* pred[i, 0]* train[i, 2])
    for j in range(numdata):
        d[j] = math.exp(-1* pred[j, 0]* train[j, 2])/ sum
        
    # model
    model = model+ a* h[k]

TypeError: unsupported operand type(s) for *: 'function' and 'function'

In [369]:
#基本関数適応
pred = []
for j in range(len(train)):
    ans = h[0](train[j,0], train[j,1])
    pred.append(ans)

pred = np.reshape(pred,(1, 4))
pred = pred.T
    
    #誤差計算
error = 0.0
for j in range(len(pred)):
    error = error + d[j]* (1-(pred[j,0]* train[j,2])) # obj = pred のときerrorが0になる
error = 0.5* error
    
    #重み計算
al = 0.5* math.log((1-error)/error)
    
    #分布更新
sum = 0.0
for i in range(numdata):
    sum = sum + math.exp(-1* pred[i, 0]* train[i, 2])
for j in range(numdata):
    d[j] = math.exp(-1* pred[j, 0]* train[j, 2])/ sum

In [370]:
print(al)
print(d)

0.5493061443340549
[ 0.71123459  0.09625514  0.09625514  0.09625514]


In [229]:
learn = []
for i in range(len(h)):
    for j in range(len(train)):
        ans = h[i](train[j,0], train[j,1])
        learn.append(ans)

learn = np.reshape(learn,(len(h), 4))
learn = learn.T
learn

array([[-1,  1,  1,  1],
       [ 1, -1,  1,  1],
       [-1, -1,  1, -1],
       [-1, -1, -1,  1]])

In [274]:
error = 0.0
for j in range(len(learn)):
    error = error + d[j]* (1-(learn[j,0]* train[j,2]))# obj = learn のときerrorが0になる
error = 0.5* error
                
al = 0.5*math.log((1-error)/error)
al

-0.4506938556659451

In [222]:
sum = 0.0
for i in range(numdata):
    sum = sum + math.exp(-1* learn[i, 0]* train[i, 2])
for j in range(numdata):    
    d[j] = math.exp(-1* learn[j, 0]* train[j, 2])/ sum